# Generated by Django 6.1.1 on 2026-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querylog',
            name='latency',
        ),
        migrations.AddField(
            model_name='querylog',
            name='file_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='querylog',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='querylog',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
